# This file provides instructions for packaging.

`return-thence`
	perl_version_from m`return::thence`;
	version_from      m`return::thence`;
	readme_from       m`return::thence`;
	test_requires     p`Test::More 0.61`;
	test_requires     p`Try::Tiny`;
	requires          p`Scope::Upper`;
.

